
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - R.generated.swift

disabled_rules:
  - force_cast
  - type_name
  - force_try
  - function_body_length
  - nesting
  - variable_name
  - control_statement
  - line_length
  - trailing_whitespace
  - statement_position
  - type_body_length
  - todo
  - valid_docs
  - missing_docs
  - file_length
  - function_parameter_count
  - cyclomatic_complexity
  - unused_closure_parameter
  - for_where
  - unused_optional_binding
  - redundant_void_return
  - void_return
  - vertical_parameter_alignment
  - unused_enumerated
  - redundant_discardable_let
  - empty_parentheses_with_trailing_closure

opt_in_rules: # some rules are only opt-in
  - force_https
  - empty_count
  - conditional_binding_cascade
  - explicit_failure_calls
  - explicit_init
  - redundant_nil_coalescing
  - syntactic_sugar

line_length: 120

custom_rules:
  explicit_failure_calls:
    name: “Avoid asserting ‘false’”
    regex: ‘((assert|precondition)\(false)’
    message: “Use assertionFailure() or preconditionFailure() instead.”
    severity: warning